version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: etl-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: etl_dynamic_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - etl-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: etl-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - etl-network

  kafka:
    image: confluentinc/confluent-local:7.6.0
    container_name: etl-kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - etl-network
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API Port (The port Spring Boot uses to send/read files)
      - "9001:9001" # Console Port (The port you use in your browser: localhost:9001)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data # Persists the files even if you turn off the container

  minio-setup:
    image: minio/mc:latest
    container_name: minio_setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to start...';
      sleep 5; 
      mc alias set myminio http://minio:9000 admin password123;
      mc mb myminio/etl-raw-data || true; 
      echo 'Bucket created successfully!';
      exit 0;
      "

volumes:
  pgdata:
  minio_data:

networks:
  etl-network:
    driver: bridge