# ===================================================================
# CONFIGURAÇÕES DO SERVIDOR
# ===================================================================
server:
  port: 8001
  servlet:
    context-path: /api

# ===================================================================
# CONFIGURAÇÕES DO SPRING (Aplicação, Banco, JPA, etc.)
# ===================================================================
spring:
  application:
    name: etl_dynamic
  
  # Perfil ativo (ex: dev, prod, test)
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/etl_dynamic_db
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  cloud:
    aws:
      credentials:
        access-key: admin
        secret-key: password123
      region:
        static: us-east-1
      s3:
        endpoint: http://localhost:9000
        bucket: etl-raw-data
        path-style-access-enabled: true
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: etl-processor-group
      auto-offset-reset: earliest # Lê desde o início se perder a ligação

    mail:
      host: localhost
      port: 1025 # Porta do Mailpit
      properties:
        mail:
          smtp:
            auth: false
            starttls:
              enable: false

  # Configurações do JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Use 'update' apenas em dev. Em prod, use 'validate' ou 'none' e ferramentas como Flyway/Liquibase.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  # Configurações de Internacionalização (Mensagens)
  messages:
    basename: messages
    encoding: UTF-8

  # Configurações do Jackson (JSON)
  jackson:
    default-property-inclusion: non_null

  web:
    error:
      include-message: always
      include-binding-errors: always

# ===================================================================
# CONFIGURAÇÕES DE LOGS
# ===================================================================
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.suaempresa.seuprojeto: DEBUG # Mude para o pacote principal da sua aplicação
  file:
    name: logs/application.log

# ===================================================================
# CONFIGURAÇÕES DO SPRING BOOT ACTUATOR (Monitoramento)
# ===================================================================
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always